language: cpp
sudo: required
os: linux
dist: trusty

matrix:
    include:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-7
          env:
              - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

before_script: make deps

script: ./configure && make

notifications:
  slack:
    secure: "HQwY2BJc3SCnomb36jGOKWMLm+78mDA+8selGBCzCNdbu3fKD9SvZUifVsV1eSe8Eckw8wCak40eDtLWgbBb1uxkbf9GllCBxUvfX9vxotiMVNcMeAkS/5z8DwE4Yw0hIak70AVbV72q6N3dvtk8J56NsiZAcJG8goKbz6jEP20="
  email:
    recipients:
      - xia-dev@cs.cmu.edu
    # options always/never/change
    on_success: always
    on_failure: always

