language: cpp
sudo: required
dist: trusty
os: linux

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y git libxml2 libxml2-dev libssl-dev python-pip python-tk python-dev python-requests python-crypto build-essential openssl swig
  - sudo pip install pynacl
  - sudo pip install networkx
    #- sudo apt-get remove libprotobuf-lite8 libprotoc8
  - wget http://launchpad.net/ubuntu/+archive/primary/+files/protobuf_2.6.1.orig.tar.gz
  - tar xvzf protobuf_2.6.1.orig.tar.gz
  - cd protobuf-2.6.1/
  - ./configure
  - make
  - sudo make install
  - sudo pip install protobuf==2.6.1
  - sudo ldconfig

script:
  -  cd ..
  - ./configure
  - make

branches:
  only:
  - v2-routing

notifications:
  slack: xia-cmu:i6KX0DyBuYJQUf5c5RUu4AOZ

